name: Tests

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt install libssl-dev
    - name: install sqlx
      run: cargo install sqlx-cli
    - name: Run tests
      run: cargo test
